[package]
name = "better_peekable"
version = "0.1.2"
edition = "2021"
license = "Apache-2.0"
keywords = ["iterator", "multipeek", "better_peekable", "peekable", "peek"]
categories = ["data-structures", "iterators", "peekable"]

